Markdown Support for Chatroom and Stylistic Changes
UCLA-IRL/ndn-workspace-solid pull request #124
Opened 2024-07-31 03:26 UTC by AnoldGH

Added markdown support to chatroom with [solid markdown](https://github.com/andi23rosca/solid-markdown) and [remarkGfm](https://github.com/remarkjs/remark-gfm).
Chatroom can now display Markdown as well as its Github extensions: 
![image](https://github.com/user-attachments/assets/b231c8a7-bb45-4cd7-aad3-082497c14f41)

Also added are some stylistic changes inspired by Github UI. Messages from local user are displayed in a light blue box much like Github discussions, while messages from foreign users are displayed in black and white.
![image](https://github.com/user-attachments/assets/cc8fd8ba-6c34-4e6f-8092-aa8f45dd0eb2)

2024-07-31 04:53 UTC, zjkmxy requested changes
Thanks, but you moved too fast. Let's first discuss if we should go this direction.

This is a temporary hold. No actual change requested.

2024-07-31 05:53 UTC, AnoldGH commented
Sure thing. This PR mainly touches on two parts:

1. Adds Markdown support. This was a TODO label in the original `chat.tsx`, which I think could be useful. This code here does it:
https://github.com/UCLA-IRL/ndn-workspace-solid/blob/a1fe54d65b6407f555afa7f9c142f8ec07c8bbd2/src/components/chat/chat.tsx#L108-L112
solid-markdown claims they are 90% similar to the original [react-markdown](https://github.com/remarkjs/react-markdown). During my tests I didn't encounter any notable issues, and so I decided to go with it.

2. Stylistic changes
I decided to make these changes upon realizing Markdown display doesn't go well with the original style, since the message box was wrapped in different colors and it was hard to distinguish between codes and texts.
Several assumptions I made during the changes:

    1. Workspace is used mainly during collaborative working, so the message box should be clear to display full segments of code, latex formula, etc.
    2. Since it is more often a working environment, some inconvenience for casual talks can be tolerated.
    3. The lack of profile choosing features is likely to continue, so the sender's username must be displayed somewhere clear

    I find Github UI and some online forums to be rather good references for these requirements, and made the changes inspired by these designs.

2024-08-04 06:00 UTC, zjkmxy approved these changes

2024-08-04 06:11 UTC, merged

2024-08-04 08:56 UTC, AnoldGH commented on src/components/chat/styles.module.scss
> +  --msg-local-border-color: #46a9ff66;
It indeed looks atrocious in dark theme, I will see what I can do later